spring:
  application:
    name: rpilab-router
  cloud:
    refresh:
      enabled: false
  http:
    client:
      connect-timeout: 30s
      read-timeout: 60s
  threads:
    virtual:
      enabled: true

app:
  routes:
  - host: "hello.127.0.0.1.nip.io:9000"
    uri: "http://localhost:8080"
    secured: true
  credentials:
  - username: admin
    password: changeme

server:
  port: ${PORT:9000}

management:
  server:
    port: ${MANAGEMENT_PORT:9001}
  endpoint:
    health:
      probes:
        add-additional-paths: true
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
